shellcode: shellcode.o
	ld -N -o shellcode shellcode.o
	strip --strip-all shellcode
	objcopy -j .text -O binary shellcode shellcode.bin
	hexdump -v -e '"\\""x" 1/1 "%02x" ""' shellcode.bin > shellcode-hex.bin
	printf '\x00' >> shellcode-hex.bin

shellcode.o: shellcode.asm
	nasm -f elf64 -o shellcode.o shellcode.asm

